//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TallerMecanico.MVVM.Base;

    public partial class cliente : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cliente()
        {
            this.factura = new HashSet<factura>();
            this.reparacion = new HashSet<reparacion>();
        }

        public int idCliente { get; set; }
        [Required(ErrorMessage = "El nombre del cliente es obligatorio")]
        [MaxLength(100)]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El/Los apellido/s del cliente son obligatorios")]
        [MaxLength(100)]
        public string apellidos { get; set; }
        [Required(ErrorMessage = "El email del cliente es obligatorio")]
        [MaxLength(80)]
        public string email { get; set; }
        public string direccion { get; set; }
        [Required(ErrorMessage = "El telefono del cliente es obligatorio")]
        [MaxLength(25)]
        public string telefono { get; set; }
        [Required(ErrorMessage = "El DNI del cliente es obligatorio")]
        [MaxLength(9)]
        public string dni { get; set; }
        public string poblacion { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<factura> factura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reparacion> reparacion { get; set; }
    }
}
