//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TallerMecanico.MVVM.Base;

    public partial class empleado : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public empleado()
        {
            this.reparacion = new HashSet<reparacion>();
        }

        public int idEmpleado { get; set; }
        [Required(ErrorMessage = "El nombre del empleado es obligatorio")]
        [MaxLength(45)]
        public string nombre { get; set; }
        [Required(ErrorMessage = "El/Los apellido/s del empleado son obligatorios")]
        [MaxLength(80)]
        public string apellidos { get; set; }
        [Required(ErrorMessage = "El nombre de usuario del empleado es obligatorio")]
        [MaxLength(45)]
        public string usuLogin { get; set; }
        [Required(ErrorMessage = "La contraseña de usuario del empleado es obligatorio")]
        [MaxLength(100)]
        public string contrasenya { get; set; }
        [Required]
        public int Rol_idRol { get; set; }

        [Required]
        public virtual rol rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reparacion> reparacion { get; set; }
    }
}
