//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TallerMecanico.Backend.Modelo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using TallerMecanico.MVVM.Base;

    public partial class pieza : PropertyChangedDataError
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public pieza()
        {
            this.reparacion = new HashSet<reparacion>();
        }

        public int idPieza { get; set; }
        [Required(ErrorMessage = "El nombre de la pieza es obligatorio")]
        [MaxLength(200)]
        public string descripcion { get; set; }
        [Required(ErrorMessage = "La cantidad de la pieza es obligatorio")]
        public int cantidad { get; set; }
        [Required(ErrorMessage = "El tipo de la pieza es obligatorio")]
        [MaxLength(45)]
        public string tipo { get; set; }
        [Required(ErrorMessage = "El precio de la pieza es obligatorio")]
        public double precio { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reparacion> reparacion { get; set; }
    }
}
